#!/bin/bash

echo "GitHub Push Helper"
echo "=================="
echo ""
echo "Your GitHub login email is: ceo@mediaintelligence.ai"
echo ""
echo "To find your GitHub username:"
echo "1. Go to https://github.com and log in with ceo@mediaintelligence.ai"
echo "2. Click your profile picture (top right)"
echo "3. Your username appears under your picture (e.g., @username)"
echo ""
echo "Common username formats:"
echo "- If your company is Media Intelligence: might be 'mediaintelligence' or 'media-intelligence'"
echo "- Could be your name: 'borismizhen' or 'bmizhen'"
echo "- Could be company-related: 'mi-ceo' or 'mizhen-mi'"
echo ""
echo "Once you know your username, run:"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/claude-gemini-assistant.git"
echo "git push -u origin main"
echo ""
echo "Or if you want to use SSH (more secure):"
echo "git remote add origin git@github.com:YOUR_USERNAME/claude-gemini-assistant.git"
echo "git push -u origin main"
echo ""
echo "Need to create the repository first?"
echo "Go to: https://github.com/new"