#!/bin/bash

echo "Claude-Gemini Assistant Extension Launcher"
echo "=========================================="
echo ""
echo "This extension provides intelligent development assistance by combining"
echo "Claude Code CLI with systematic project analysis following Gemini workflow methodology."
echo ""
echo "To launch the extension in VS Code:"
echo ""
echo "1. Open VS Code"
echo "2. File → Open Folder → Select this folder (claude-gemini-assistant)"
echo "3. Press F5 to launch the Extension Development Host"
echo ""
echo "OR use the command line:"
echo ""
echo "cd $(pwd)"
echo "code ."
echo ""
echo "Then press F5 in VS Code"
echo ""
echo "Current directory: $(pwd)"
echo ""
echo "Optional: Build the TypeScript first with 'npm run compile' if you prefer a precompiled build."
echo ""
echo "Note: The extension has some TypeScript compilation warnings that don't prevent it from running."
echo "The core functionality is available despite these warnings."